"""Agent — the basic unit of the simulation."""

from __future__ import annotations

import json
import math
import random
import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from aibm.activity import VALID_OUT_OF_HOME_TYPES, Activity
from aibm.day_plan import DayPlan
from aibm.llm import LLMClient, create_client
from aibm.poi import POI
from aibm.sampling import sample_destinations
from aibm.skim import Skim
from aibm.tour import Tour
from aibm.trip import Trip
from aibm.zone import Zone

if TYPE_CHECKING:
    from aibm.household import Household

_ACTIVITY_MIN_DURATIONS: dict[str, str] = {
    "work": "360–540 min (6–9 h)",
    "school": "300–420 min (5–7 h)",
    "shopping": "15–60 min",
    "leisure": "60–180 min",
    "personal_business": "15–45 min",
    "eating_out": "30–90 min",
    "escort": "10–30 min",
}


@dataclass
class ModeOption:
    """One row of mode-choice input data.

    Attributes:
        mode: Name of the travel mode (e.g. "car", "bike", "transit").
        travel_time: Travel time in minutes for this mode.
    """

    mode: str
    travel_time: float


@dataclass
class ModeChoice:
    """The result of an LLM-powered mode choice.

    Attributes:
        option: The chosen ModeOption.
        reasoning: A short story from the agent explaining the choice.
    """

    option: ModeOption
    reasoning: str


@dataclass
class Agent:
    """A single agent in the simulation.

    Attributes:
        name: Human-readable label.
        model: LLM model name (e.g. ``"gemini-2.5-flash-lite"`` or
            ``"claude-sonnet-4-20250514"``).  Names starting with
            ``"claude"`` automatically use the Anthropic API.
        id: Unique identifier (auto-generated if not supplied).
        age: Age in years (0 means not yet assigned).
        employment: Employment status — one of ``"employed"``,
            ``"student"``, ``"retired"``, or ``"unemployed"``.
        has_license: Whether the agent holds a driving licence.
        home_zone: Zone id of the agent's residence (set via Household).
        work_zone: Zone id of the workplace (set during synthesis).
        school_zone: Zone id of the school (set during synthesis).
        persona: Short behavioural profile generated by the LLM.
    """

    name: str
    model: str = "gemini-2.5-flash-lite"
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    age: int = 0
    employment: str = "unemployed"
    has_license: bool = False
    home_zone: str | None = None
    work_zone: str | None = None
    school_zone: str | None = None
    persona: str | None = None

    def __repr__(self) -> str:
        return f"Agent(id={self.id!r}, name={self.name!r})"

    def _build_background(self, household: Household | None = None) -> str:
        """Build a background description from agent and household attributes."""
        lines: list[str] = []
        if self.age > 0:
            lines.append(f"Age: {self.age}")
        lines.append(f"Employment: {self.employment}")
        lines.append(f"Has driving licence: {'yes' if self.has_license else 'no'}")
        if self.home_zone:
            lines.append(f"Home zone: {self.home_zone}")
        if self.work_zone:
            lines.append(f"Work zone: {self.work_zone}")
        if self.school_zone:
            lines.append(f"School zone: {self.school_zone}")
        if self.persona:
            lines.append(f"Persona: {self.persona}")
        if household is not None:
            lines.append(f"Household vehicles: {household.num_vehicles}")
            lines.append(f"Household income: {household.income_level}")
        return "\n".join(lines)

    def generate_persona(
        self,
        client: LLMClient | None = None,
        household: Household | None = None,
        overwrite: bool = False,
    ) -> str:
        """Ask the LLM to create a short behavioural persona.

        The persona is a 1-2 sentence profile that captures travel
        habits and preferences based on demographics and household
        context.  The result is stored in ``self.persona`` and also
        returned.

        If a persona already exists the LLM call is skipped and
        the cached value is returned, unless *overwrite* is True.

        Args:
            client: An :class:`~aibm.llm.LLMClient`.  When *None*
                one is created automatically based on ``self.model``.
            household: Optional household for richer context.
            overwrite: Re-generate even when a persona already
                exists.

        Returns:
            The generated persona string.
        """
        if self.persona is not None and not overwrite:
            return self.persona

        if client is None:
            client = create_client(self.model)

        background = self._build_background(household)
        prompt = (
            f"You are creating a behavioural profile for "
            f"{self.name}.\n"
            f"Demographics:\n{background}\n\n"
            "Write a 1-2 sentence persona describing this "
            "person's travel habits, preferences, and daily "
            "routine. Be specific and grounded in the "
            "demographics above."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "persona": {"type": "string"},
                },
                "required": ["persona"],
            },
        )

        data = json.loads(text)
        self.persona = data["persona"]
        return self.persona

    def choose_mode(
        self,
        options: list[ModeOption],
        client: LLMClient | None = None,
        household: Household | None = None,
    ) -> ModeChoice:
        """Ask the LLM to pick a travel mode and explain why.

        Args:
            options: Available modes with their travel times.
            client: An :class:`~aibm.llm.LLMClient`.  When *None*
                one is created automatically based on ``self.model``.
            household: Optional household that supplies vehicle
                count and income level for richer decision context.

        Returns:
            A ``ModeChoice`` with the selected option and reasoning.

        Raises:
            ValueError: If options is empty.
        """
        if not options:
            raise ValueError("options must contain at least one ModeOption")

        if client is None:
            client = create_client(self.model)

        background = self._build_background(household)
        options_text = "\n".join(
            f"- {opt.mode}: {opt.travel_time} minutes" for opt in options
        )
        prompt = (
            f"You are {self.name}, deciding how to travel "
            "today.\n"
            f"Background:\n{background}\n\n"
            f"Available options:\n{options_text}\n\n"
            "Pick exactly one mode. Respond with:\n"
            '- "reasoning": a short personal story '
            "(2-3 sentences) explaining your choice.\n"
            '- "choice": the mode name exactly as listed '
            "above."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "reasoning": {"type": "string"},
                    "choice": {"type": "string"},
                },
                "required": ["reasoning", "choice"],
            },
        )

        data = json.loads(text)
        chosen_name: str = data["choice"]
        chosen_option = next(opt for opt in options if opt.mode == chosen_name)
        return ModeChoice(option=chosen_option, reasoning=data["reasoning"])

    def choose_work_zone(
        self,
        zones: list[Zone],
        travel_times: dict[str, dict[str, float]],
        client: LLMClient | None = None,
        overwrite: bool = False,
    ) -> str:
        """Ask the LLM to pick a work zone for this agent.

        If a work zone is already set the LLM call is skipped and
        the cached value is returned, unless *overwrite* is True.

        Args:
            zones: Candidate work zones.
            travel_times: Zone id -> mode -> minutes.
            client: An :class:`~aibm.llm.LLMClient`.
            overwrite: Re-generate even when a work zone is
                already set.

        Returns:
            The chosen zone id (stored as ``self.work_zone``).

        Raises:
            ValueError: If not employed or zones is empty.
        """
        if self.employment != "employed":
            raise ValueError("choose_work_zone only applies to employed agents")
        if self.work_zone is not None and not overwrite:
            return self.work_zone
        return self._choose_long_term_zone(zones, travel_times, "work", client)

    def choose_school_zone(
        self,
        zones: list[Zone],
        travel_times: dict[str, dict[str, float]],
        client: LLMClient | None = None,
        overwrite: bool = False,
    ) -> str:
        """Ask the LLM to pick a school zone for this agent.

        If a school zone is already set the LLM call is skipped
        and the cached value is returned, unless *overwrite* is
        True.

        Args:
            zones: Candidate school zones.
            travel_times: Zone id -> mode -> minutes.
            client: An :class:`~aibm.llm.LLMClient`.
            overwrite: Re-generate even when a school zone is
                already set.

        Returns:
            The chosen zone id (stored as ``self.school_zone``).

        Raises:
            ValueError: If not a student or zones is empty.
        """
        if self.employment != "student":
            raise ValueError("choose_school_zone only applies to student agents")
        if self.school_zone is not None and not overwrite:
            return self.school_zone
        return self._choose_long_term_zone(zones, travel_times, "school", client)

    def _choose_long_term_zone(
        self,
        zones: list[Zone],
        travel_times: dict[str, dict[str, float]],
        purpose: str,
        client: LLMClient | None = None,
    ) -> str:
        """Shared logic for choosing a work or school zone."""
        if not zones:
            raise ValueError("zones must contain at least one Zone")

        if client is None:
            client = create_client(self.model)

        background = self._build_background()
        zones_text = "\n".join(
            f"- {z.id}: {z.name} ({', '.join(k for k, v in z.land_use.items() if v)})"
            for z in zones
        )
        travel_text = "\n".join(
            f"- {zid}: "
            + ", ".join(f"{mode} {mins:.0f} min" for mode, mins in modes.items())
            for zid, modes in travel_times.items()
        )
        prompt = (
            f"You are {self.name}, choosing a {purpose} "
            "location.\n"
            f"Background:\n{background}\n\n"
            f"Candidate zones:\n{zones_text}\n\n"
            f"Travel times from home:\n{travel_text}\n\n"
            f"Pick exactly one zone id for your {purpose}. "
            "Respond with the zone id and your reasoning."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "zone_id": {"type": "string"},
                    "reasoning": {"type": "string"},
                },
                "required": ["zone_id", "reasoning"],
            },
        )

        data = json.loads(text)
        chosen_id: str = data["zone_id"]

        if purpose == "work":
            self.work_zone = chosen_id
        else:
            self.school_zone = chosen_id
        return chosen_id

    def generate_activities(
        self,
        client: LLMClient | None = None,
    ) -> list[Activity]:
        """Ask the LLM to generate today's activity list.

        Mandatory activities (work / school) always appear. The
        LLM fills in discretionary ones such as shopping or
        leisure.

        Args:
            client: An :class:`~aibm.llm.LLMClient`.

        Returns:
            A non-empty list of ``Activity`` objects.
        """
        if client is None:
            client = create_client(self.model)

        background = self._build_background()
        valid_types = sorted(VALID_OUT_OF_HOME_TYPES)
        types_list = ", ".join(valid_types)
        prompt = (
            f"You are {self.name}, planning your day.\n"
            f"Background:\n{background}\n\n"
            "Only include out-of-home activities. "
            "Include mandatory activities: work if you are "
            "employed, school if you are a student. "
            "Also include any discretionary activities. "
            "For each activity specify whether it has a "
            "flexible time (is_flexible true) or is fixed "
            "(is_flexible false). Work and school are always "
            "fixed (is_flexible false).\n"
            f"Allowed activity types: {types_list}."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "activities": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "enum": valid_types,
                                },
                                "is_flexible": {
                                    "type": "boolean",
                                },
                            },
                            "required": [
                                "type",
                                "is_flexible",
                            ],
                        },
                    }
                },
                "required": ["activities"],
            },
        )

        data = json.loads(text)

        activities: list[Activity] = []
        for item in data["activities"]:
            act_type = item["type"].lower().strip()

            # Skip work/school if agent has no zone assigned
            if act_type == "work" and self.work_zone is None:
                continue
            if act_type == "school" and self.school_zone is None:
                continue

            activity = Activity(
                type=act_type,
                is_flexible=item["is_flexible"],
            )
            if activity.type == "work":
                activity.location = self.work_zone
                activity.is_flexible = False
            elif activity.type == "school":
                activity.location = self.school_zone
                activity.is_flexible = False
            activities.append(activity)

        return activities

    def choose_destination(
        self,
        activity: Activity,
        candidates: list[Zone] | None = None,
        client: LLMClient | None = None,
        pois: list[POI] | None = None,
        skims: list[Skim] | None = None,
        current_zone: str | None = None,
        n_candidates: int = 10,
        rng: random.Random | None = None,
    ) -> Activity:
        """Ask the LLM to pick a destination for an activity.

        Supply *candidates* (zones), *pois*, or both.  When POIs
        are provided they are presented to the LLM as specific
        named locations (e.g. individual shops or restaurants).

        Args:
            activity: The activity needing a destination.
            candidates: Available zones to choose from.
            client: An :class:`~aibm.llm.LLMClient`.
            pois: Points of interest to choose from.
            skims: Skim matrices (one per mode) for travel
                time lookups.
            current_zone: Agent's current location zone id.
                Falls back to ``self.home_zone`` when *None*.
            n_candidates: Max candidates to show the LLM.
            rng: Optional seeded RNG for reproducible sampling.

        Returns:
            The same ``activity`` with ``location`` set.

        Raises:
            ValueError: If both *candidates* and *pois* are
                empty / ``None``.
        """
        has_zones = bool(candidates)
        has_pois = bool(pois)
        if not has_zones and not has_pois:
            raise ValueError("Provide at least one Zone or POI as candidate")

        if client is None:
            client = create_client(self.model)

        # Sample candidates down to n_candidates.
        if has_zones:
            assert candidates is not None
            candidates = sample_destinations(candidates, n=n_candidates, rng=rng)
        if has_pois:
            assert pois is not None
            pois = sample_destinations(pois, n=n_candidates, rng=rng)

        background = self._build_background()

        # --- build the options list shown to the LLM ------
        options_lines: list[str] = []
        if candidates:
            for z in candidates:
                lu = ", ".join(k for k, v in z.land_use.items() if v)
                options_lines.append(f"- zone:{z.id}: {z.name} ({lu})")
        if pois:
            for p in pois:
                label = p.name if p.name else "unnamed"
                options_lines.append(f"- poi:{p.id}: {label} [{p.activity_type}]")
        options_text = "\n".join(options_lines)

        # --- build travel time block --------------------
        travel_block = ""
        origin = current_zone or self.home_zone
        if skims and origin:
            tt_lines: list[str] = []
            if candidates:
                for z in candidates:
                    parts = []
                    for sk in skims:
                        tt = sk.travel_time(origin, z.id)
                        if tt < float("inf"):
                            parts.append(f"{sk.mode} {tt:.0f} min")
                    if parts:
                        tt_lines.append(f"- zone:{z.id}: " + ", ".join(parts))
            if pois:
                for p in pois:
                    if p.zone_id is None:
                        continue
                    parts = []
                    for sk in skims:
                        tt = sk.travel_time(origin, p.zone_id)
                        if tt < float("inf"):
                            parts.append(f"{sk.mode} {tt:.0f} min")
                    if parts:
                        tt_lines.append(f"- poi:{p.id}: " + ", ".join(parts))
            if tt_lines:
                travel_block = (
                    "\nTravel times from your current "
                    "location:\n" + "\n".join(tt_lines) + "\n"
                )

        time_text = ""
        if activity.start_time is not None and activity.end_time is not None:
            time_text = (
                f"Scheduled: {activity.start_time:.0f}"
                f"\u2013{activity.end_time:.0f} "
                "(minutes from midnight)\n"
            )

        prompt = (
            f"You are {self.name}, choosing where to do an "
            "activity.\n"
            f"Background:\n{background}\n\n"
            f"Activity type: {activity.type}\n" + time_text + "\n"
            f"Candidate destinations:\n{options_text}\n"
            + travel_block
            + "\nPick exactly one id (including the zone: or "
            "poi: prefix) from the list above that best fits "
            "this activity. Respond with the id and your "
            "reasoning."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "destination_id": {"type": "string"},
                    "reasoning": {"type": "string"},
                },
                "required": [
                    "destination_id",
                    "reasoning",
                ],
            },
        )

        data = json.loads(text)
        raw_id: str = data["destination_id"]
        # Strip the prefix so we get a plain id.
        if raw_id.startswith("poi:") or raw_id.startswith("zone:"):
            chosen_id = raw_id.split(":", 1)[1]
        else:
            chosen_id = raw_id

        poi_lookup = {p.id: p for p in (pois or [])}
        if chosen_id in poi_lookup:
            poi = poi_lookup[chosen_id]
            activity.poi_id = poi.id
            activity.location = poi.zone_id if poi.zone_id is not None else poi.id
        else:
            activity.location = chosen_id
        return activity

    def schedule_activities(
        self,
        activities: list[Activity],
        client: LLMClient | None = None,
        skims: list[Skim] | None = None,
    ) -> DayPlan:
        """Ask the LLM to assign start/end times to activities.

        An empty input list returns an empty ``DayPlan`` without
        calling the LLM.

        Args:
            activities: Activities to schedule.
            client: An :class:`~aibm.llm.LLMClient`.
            skims: Optional skim matrices used to include leg
                travel times in the scheduling prompt.

        Returns:
            A ``DayPlan`` sorted by ``start_time``.
        """
        if not activities:
            return DayPlan(activities=[])

        if client is None:
            client = create_client(self.model)

        background = self._build_background()
        activities_text = "\n".join(
            f"- {a.type} (flexible: {'yes' if a.is_flexible else 'no'})"
            for a in activities
        )

        travel_text = ""
        if skims:
            legs = []
            for a, b in zip(activities, activities[1:]):
                if a.location and b.location:
                    parts = []
                    for sk in skims:
                        tt = sk.travel_time(a.location, b.location)
                        if tt < math.inf:
                            parts.append(f"{sk.mode} {tt:.0f} min")
                    if parts:
                        legs.append(f"- {a.type} → {b.type}: {', '.join(parts)}")
            if legs:
                travel_text = (
                    "\nTravel times between consecutive activities:\n"
                    + "\n".join(legs)
                    + "\n"
                )

        seen_types = {a.type for a in activities}
        dur_lines = [
            f"- {t}: {hint}"
            for t, hint in _ACTIVITY_MIN_DURATIONS.items()
            if t in seen_types
        ]
        duration_text = ""
        if dur_lines:
            duration_text = (
                "\nSuggested minimum durations:\n" + "\n".join(dur_lines) + "\n"
            )

        prompt = (
            f"You are {self.name}, scheduling your day.\n"
            f"Background:\n{background}\n\n"
            f"Activities to schedule:\n{activities_text}\n"
            f"{travel_text}"
            f"{duration_text}\n"
            "Assign a start_time and end_time (in minutes from midnight, "
            "e.g. 480 = 08:00) to each activity. "
            "Ensure each activity starts at least as late as the previous "
            "activity's end_time plus the travel time to reach it. "
            "Fixed activities have realistic fixed hours; flexible ones fill "
            "the remaining time. Return them in chronological order."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "schedule": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {"type": "string"},
                                "start_time": {"type": "number"},
                                "end_time": {"type": "number"},
                            },
                            "required": [
                                "type",
                                "start_time",
                                "end_time",
                            ],
                        },
                    }
                },
                "required": ["schedule"],
            },
        )

        data = json.loads(text)

        for i, item in enumerate(data["schedule"]):
            if i < len(activities):
                activities[i].start_time = item["start_time"]
                activities[i].end_time = item["end_time"]

        sorted_activities = sorted(
            activities,
            key=lambda a: a.start_time if a.start_time is not None else 0,
        )
        return DayPlan(activities=sorted_activities)

    def build_tours(self, day_plan: DayPlan) -> DayPlan:
        """Convert scheduled activities into Trip/Tour objects.

        Builds the sequence home → activity₁ → activity₂ → … → home,
        creating a Trip between each consecutive pair of locations.
        A new Tour starts each time the agent departs from home.

        No LLM call is made — this is pure logic.

        Args:
            day_plan: A DayPlan with scheduled, located activities.

        Returns:
            The same ``day_plan`` with ``tours`` populated.

        Raises:
            ValueError: If ``home_zone`` is not set or any activity
                is missing a location or times.
        """
        if self.home_zone is None:
            raise ValueError("home_zone must be set before building tours")

        for act in day_plan.activities:
            if act.location is None:
                raise ValueError(f"Activity '{act.type}' has no location")
            if act.start_time is None or act.end_time is None:
                raise ValueError(f"Activity '{act.type}' has no scheduled times")

        if not day_plan.activities:
            day_plan.tours = []
            return day_plan

        # Build location sequence: home → activities → home
        locations: list[str] = [self.home_zone]
        for act in day_plan.activities:
            assert act.location is not None
            locations.append(act.location)
        locations.append(self.home_zone)

        # Build departure times: leave home before first activity,
        # leave each activity at its end_time, final arrival home
        times: list[float] = [day_plan.activities[0].start_time or 0]
        for act in day_plan.activities:
            assert act.end_time is not None
            times.append(act.end_time)

        # Create trips between consecutive locations
        all_trips: list[Trip] = []
        for i in range(len(locations) - 1):
            trip = Trip(
                origin=locations[i],
                destination=locations[i + 1],
                departure_time=times[i],
            )
            all_trips.append(trip)

        # Group into tours: new tour each departure from home
        tours: list[Tour] = []
        current_trips: list[Trip] = []
        for trip in all_trips:
            current_trips.append(trip)
            if trip.destination == self.home_zone:
                tours.append(
                    Tour(
                        trips=current_trips,
                        home_zone=self.home_zone,
                    )
                )
                current_trips = []

        # Unclosed tour (shouldn't happen with home appended)
        if current_trips:
            tours.append(Tour(trips=current_trips, home_zone=self.home_zone))

        day_plan.tours = tours
        return day_plan

    def choose_tour_mode(
        self,
        tour: Tour,
        options: list[ModeOption],
        client: LLMClient | None = None,
        household: Household | None = None,
    ) -> ModeChoice:
        """Choose one mode for the entire tour.

        Calls :meth:`choose_mode` once for the first (outbound) trip
        and applies the chosen mode to every trip in the tour.

        Args:
            tour: The tour to assign a mode to.
            options: Available modes with travel times.
            client: An :class:`~aibm.llm.LLMClient`.
            household: Optional household context.

        Returns:
            The :class:`ModeChoice` for the tour.

        Raises:
            ValueError: If the tour has no trips or options
                is empty.
        """
        if not tour.trips:
            raise ValueError("tour must contain at least one trip")

        choice = self.choose_mode(options, client=client, household=household)
        for trip in tour.trips:
            trip.mode = choice.option.mode
        return choice
