"""Agent — the basic unit of the simulation."""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from google import genai
from google.genai import types

if TYPE_CHECKING:
    from aibm.household import Household


@dataclass
class ModeOption:
    """One row of mode-choice input data.

    Attributes:
        mode: Name of the travel mode (e.g. "car", "bike", "transit").
        travel_time: Travel time in minutes for this mode.
    """

    mode: str
    travel_time: float


@dataclass
class ModeChoice:
    """The result of an LLM-powered mode choice.

    Attributes:
        option: The chosen ModeOption.
        reasoning: A short story from the agent explaining the choice.
    """

    option: ModeOption
    reasoning: str


@dataclass
class Agent:
    """A single agent in the simulation.

    Attributes:
        name: Human-readable label.
        model: Gemini model used for decision-making.
        id: Unique identifier (auto-generated if not supplied).
        age: Age in years (0 means not yet assigned).
        employment: Employment status — one of ``"employed"``,
            ``"student"``, ``"retired"``, or ``"unemployed"``.
        has_license: Whether the agent holds a driving licence.
        home_zone: Zone id of the agent's residence (set via Household).
        work_zone: Zone id of the workplace (set during synthesis).
        school_zone: Zone id of the school (set during synthesis).
        persona: Short behavioural profile generated by the LLM.
    """

    name: str
    model: str = "gemini-2.5-flash-lite"
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    age: int = 0
    employment: str = "unemployed"
    has_license: bool = False
    home_zone: str | None = None
    work_zone: str | None = None
    school_zone: str | None = None
    persona: str | None = None

    def __repr__(self) -> str:
        return f"Agent(id={self.id!r}, name={self.name!r})"

    def _build_background(self, household: Household | None = None) -> str:
        """Build a background description from agent and household attributes."""
        lines: list[str] = []
        if self.age > 0:
            lines.append(f"Age: {self.age}")
        lines.append(f"Employment: {self.employment}")
        lines.append(f"Has driving licence: {'yes' if self.has_license else 'no'}")
        if self.home_zone:
            lines.append(f"Home zone: {self.home_zone}")
        if self.work_zone:
            lines.append(f"Work zone: {self.work_zone}")
        if self.school_zone:
            lines.append(f"School zone: {self.school_zone}")
        if self.persona:
            lines.append(f"Persona: {self.persona}")
        if household is not None:
            lines.append(f"Household vehicles: {household.num_vehicles}")
            lines.append(f"Household income: {household.income_level}")
        return "\n".join(lines)

    def generate_persona(
        self,
        client: genai.Client | None = None,
        household: Household | None = None,
    ) -> str:
        """Ask the LLM to create a short behavioural persona for this agent.

        The persona is a 1-2 sentence profile that captures travel habits and
        preferences based on the agent's demographics and household context.
        The result is stored in ``self.persona`` and also returned.

        Args:
            client: A ``genai.Client`` instance.  A fresh one is created when
                ``None`` is passed (reads ``GEMINI_API_KEY`` from the environment).
            household: Optional household for richer context.

        Returns:
            The generated persona string.
        """
        if client is None:
            client = genai.Client()

        background = self._build_background(household)
        prompt = (
            f"You are creating a behavioural profile for {self.name}.\n"
            f"Demographics:\n{background}\n\n"
            "Write a 1-2 sentence persona describing this person's travel "
            "habits, preferences, and daily routine. Be specific and "
            "grounded in the demographics above."
        )

        response = client.models.generate_content(
            model=self.model,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema={
                    "type": "object",
                    "properties": {
                        "persona": {"type": "string"},
                    },
                    "required": ["persona"],
                },
            ),
        )

        if response.text is None:
            raise ValueError("LLM returned an empty response")
        data = json.loads(response.text)
        self.persona = data["persona"]
        return self.persona

    def choose_mode(
        self,
        options: list[ModeOption],
        client: genai.Client | None = None,
        household: Household | None = None,
    ) -> ModeChoice:
        """Ask a Gemini LLM to pick a travel mode and explain the reasoning.

        The LLM receives the agent's background (demographics, household
        context) and each option with its travel time, then returns JSON
        with two fields: ``reasoning`` (a short personal story) and
        ``choice`` (the mode name).

        Args:
            options: Available modes with their travel times.
            client: A ``genai.Client`` instance. A fresh one is created when
                ``None`` is passed (reads ``GEMINI_API_KEY`` from the environment).
            household: Optional household that supplies vehicle count and
                income level for richer decision context.

        Returns:
            A ``ModeChoice`` with the selected ``ModeOption`` and the reasoning.

        Raises:
            ValueError: If options is empty.
        """
        if not options:
            raise ValueError("options must contain at least one ModeOption")

        if client is None:
            client = genai.Client()

        background = self._build_background(household)
        options_text = "\n".join(
            f"- {opt.mode}: {opt.travel_time} minutes" for opt in options
        )
        prompt = (
            f"You are {self.name}, deciding how to travel today.\n"
            f"Background:\n{background}\n\n"
            f"Available options:\n{options_text}\n\n"
            "Pick exactly one mode. Respond with:\n"
            '- "reasoning": a short personal story (2-3 sentences) explaining'
            " your choice.\n"
            '- "choice": the mode name exactly as listed above.'
        )

        response = client.models.generate_content(
            model=self.model,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema={
                    "type": "object",
                    "properties": {
                        "reasoning": {"type": "string"},
                        "choice": {"type": "string"},
                    },
                    "required": ["reasoning", "choice"],
                },
            ),
        )

        if response.text is None:
            raise ValueError("LLM returned an empty response")
        data = json.loads(response.text)
        chosen_name: str = data["choice"]
        chosen_option = next(opt for opt in options if opt.mode == chosen_name)
        return ModeChoice(option=chosen_option, reasoning=data["reasoning"])
