"""Agent — the basic unit of the simulation."""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from aibm.activity import Activity
from aibm.day_plan import DayPlan
from aibm.llm import LLMClient, create_client
from aibm.tour import Tour
from aibm.trip import Trip
from aibm.zone import Zone

if TYPE_CHECKING:
    from aibm.household import Household


@dataclass
class ModeOption:
    """One row of mode-choice input data.

    Attributes:
        mode: Name of the travel mode (e.g. "car", "bike", "transit").
        travel_time: Travel time in minutes for this mode.
    """

    mode: str
    travel_time: float


@dataclass
class ModeChoice:
    """The result of an LLM-powered mode choice.

    Attributes:
        option: The chosen ModeOption.
        reasoning: A short story from the agent explaining the choice.
    """

    option: ModeOption
    reasoning: str


@dataclass
class Agent:
    """A single agent in the simulation.

    Attributes:
        name: Human-readable label.
        model: LLM model name (e.g. ``"gemini-2.5-flash-lite"`` or
            ``"claude-sonnet-4-20250514"``).  Names starting with
            ``"claude"`` automatically use the Anthropic API.
        id: Unique identifier (auto-generated if not supplied).
        age: Age in years (0 means not yet assigned).
        employment: Employment status — one of ``"employed"``,
            ``"student"``, ``"retired"``, or ``"unemployed"``.
        has_license: Whether the agent holds a driving licence.
        home_zone: Zone id of the agent's residence (set via Household).
        work_zone: Zone id of the workplace (set during synthesis).
        school_zone: Zone id of the school (set during synthesis).
        persona: Short behavioural profile generated by the LLM.
    """

    name: str
    model: str = "gemini-2.5-flash-lite"
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    age: int = 0
    employment: str = "unemployed"
    has_license: bool = False
    home_zone: str | None = None
    work_zone: str | None = None
    school_zone: str | None = None
    persona: str | None = None

    def __repr__(self) -> str:
        return f"Agent(id={self.id!r}, name={self.name!r})"

    def _build_background(self, household: Household | None = None) -> str:
        """Build a background description from agent and household attributes."""
        lines: list[str] = []
        if self.age > 0:
            lines.append(f"Age: {self.age}")
        lines.append(f"Employment: {self.employment}")
        lines.append(f"Has driving licence: {'yes' if self.has_license else 'no'}")
        if self.home_zone:
            lines.append(f"Home zone: {self.home_zone}")
        if self.work_zone:
            lines.append(f"Work zone: {self.work_zone}")
        if self.school_zone:
            lines.append(f"School zone: {self.school_zone}")
        if self.persona:
            lines.append(f"Persona: {self.persona}")
        if household is not None:
            lines.append(f"Household vehicles: {household.num_vehicles}")
            lines.append(f"Household income: {household.income_level}")
        return "\n".join(lines)

    def generate_persona(
        self,
        client: LLMClient | None = None,
        household: Household | None = None,
    ) -> str:
        """Ask the LLM to create a short behavioural persona.

        The persona is a 1-2 sentence profile that captures travel
        habits and preferences based on demographics and household
        context.  The result is stored in ``self.persona`` and also
        returned.

        Args:
            client: An :class:`~aibm.llm.LLMClient`.  When *None*
                one is created automatically based on ``self.model``.
            household: Optional household for richer context.

        Returns:
            The generated persona string.
        """
        if client is None:
            client = create_client(self.model)

        background = self._build_background(household)
        prompt = (
            f"You are creating a behavioural profile for "
            f"{self.name}.\n"
            f"Demographics:\n{background}\n\n"
            "Write a 1-2 sentence persona describing this "
            "person's travel habits, preferences, and daily "
            "routine. Be specific and grounded in the "
            "demographics above."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "persona": {"type": "string"},
                },
                "required": ["persona"],
            },
        )

        data = json.loads(text)
        self.persona = data["persona"]
        return self.persona

    def choose_mode(
        self,
        options: list[ModeOption],
        client: LLMClient | None = None,
        household: Household | None = None,
    ) -> ModeChoice:
        """Ask the LLM to pick a travel mode and explain why.

        Args:
            options: Available modes with their travel times.
            client: An :class:`~aibm.llm.LLMClient`.  When *None*
                one is created automatically based on ``self.model``.
            household: Optional household that supplies vehicle
                count and income level for richer decision context.

        Returns:
            A ``ModeChoice`` with the selected option and reasoning.

        Raises:
            ValueError: If options is empty.
        """
        if not options:
            raise ValueError("options must contain at least one ModeOption")

        if client is None:
            client = create_client(self.model)

        background = self._build_background(household)
        options_text = "\n".join(
            f"- {opt.mode}: {opt.travel_time} minutes" for opt in options
        )
        prompt = (
            f"You are {self.name}, deciding how to travel "
            "today.\n"
            f"Background:\n{background}\n\n"
            f"Available options:\n{options_text}\n\n"
            "Pick exactly one mode. Respond with:\n"
            '- "reasoning": a short personal story '
            "(2-3 sentences) explaining your choice.\n"
            '- "choice": the mode name exactly as listed '
            "above."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "reasoning": {"type": "string"},
                    "choice": {"type": "string"},
                },
                "required": ["reasoning", "choice"],
            },
        )

        data = json.loads(text)
        chosen_name: str = data["choice"]
        chosen_option = next(opt for opt in options if opt.mode == chosen_name)
        return ModeChoice(option=chosen_option, reasoning=data["reasoning"])

    def choose_work_zone(
        self,
        zones: list[Zone],
        travel_times: dict[str, dict[str, float]],
        client: LLMClient | None = None,
    ) -> str:
        """Ask the LLM to pick a work zone for this agent.

        Args:
            zones: Candidate work zones.
            travel_times: Zone id -> mode -> minutes.
            client: An :class:`~aibm.llm.LLMClient`.

        Returns:
            The chosen zone id (stored as ``self.work_zone``).

        Raises:
            ValueError: If not employed or zones is empty.
        """
        if self.employment != "employed":
            raise ValueError("choose_work_zone only applies to employed agents")
        return self._choose_long_term_zone(zones, travel_times, "work", client)

    def choose_school_zone(
        self,
        zones: list[Zone],
        travel_times: dict[str, dict[str, float]],
        client: LLMClient | None = None,
    ) -> str:
        """Ask the LLM to pick a school zone for this agent.

        Args:
            zones: Candidate school zones.
            travel_times: Zone id -> mode -> minutes.
            client: An :class:`~aibm.llm.LLMClient`.

        Returns:
            The chosen zone id (stored as ``self.school_zone``).

        Raises:
            ValueError: If not a student or zones is empty.
        """
        if self.employment != "student":
            raise ValueError("choose_school_zone only applies to student agents")
        return self._choose_long_term_zone(zones, travel_times, "school", client)

    def _choose_long_term_zone(
        self,
        zones: list[Zone],
        travel_times: dict[str, dict[str, float]],
        purpose: str,
        client: LLMClient | None = None,
    ) -> str:
        """Shared logic for choosing a work or school zone."""
        if not zones:
            raise ValueError("zones must contain at least one Zone")

        if client is None:
            client = create_client(self.model)

        background = self._build_background()
        zones_text = "\n".join(
            f"- {z.id}: {z.name} ({', '.join(k for k, v in z.land_use.items() if v)})"
            for z in zones
        )
        travel_text = "\n".join(
            f"- {zid}: "
            + ", ".join(f"{mode} {mins:.0f} min" for mode, mins in modes.items())
            for zid, modes in travel_times.items()
        )
        prompt = (
            f"You are {self.name}, choosing a {purpose} "
            "location.\n"
            f"Background:\n{background}\n\n"
            f"Candidate zones:\n{zones_text}\n\n"
            f"Travel times from home:\n{travel_text}\n\n"
            f"Pick exactly one zone id for your {purpose}. "
            "Respond with the zone id and your reasoning."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "zone_id": {"type": "string"},
                    "reasoning": {"type": "string"},
                },
                "required": ["zone_id", "reasoning"],
            },
        )

        data = json.loads(text)
        chosen_id: str = data["zone_id"]

        if purpose == "work":
            self.work_zone = chosen_id
        else:
            self.school_zone = chosen_id
        return chosen_id

    def generate_activities(
        self,
        client: LLMClient | None = None,
    ) -> list[Activity]:
        """Ask the LLM to generate today's activity list.

        Mandatory activities (work / school) always appear. The
        LLM fills in discretionary ones such as shopping or
        leisure.

        Args:
            client: An :class:`~aibm.llm.LLMClient`.

        Returns:
            A non-empty list of ``Activity`` objects.
        """
        if client is None:
            client = create_client(self.model)

        background = self._build_background()
        prompt = (
            f"You are {self.name}, planning your day.\n"
            f"Background:\n{background}\n\n"
            "List the activities you will do today. "
            "Include mandatory activities: work if you are "
            "employed, school if you are a student. "
            "Also include any discretionary activities such as "
            "shopping or leisure. For each activity specify "
            "whether it has a flexible time (is_flexible true) "
            "or is fixed (is_flexible false). "
            "Work and school are always fixed "
            "(is_flexible false)."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "activities": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {"type": "string"},
                                "is_flexible": {"type": "boolean"},
                            },
                            "required": [
                                "type",
                                "is_flexible",
                            ],
                        },
                    }
                },
                "required": ["activities"],
            },
        )

        data = json.loads(text)

        activities: list[Activity] = []
        for item in data["activities"]:
            activity = Activity(
                type=item["type"],
                is_flexible=item["is_flexible"],
            )
            if activity.type == "work" and self.work_zone is not None:
                activity.location = self.work_zone
                activity.is_flexible = False
            elif activity.type == "school" and self.school_zone is not None:
                activity.location = self.school_zone
                activity.is_flexible = False
            activities.append(activity)

        return activities

    def choose_destination(
        self,
        activity: Activity,
        candidates: list[Zone],
        client: LLMClient | None = None,
    ) -> Activity:
        """Ask the LLM to pick a destination for an activity.

        Args:
            activity: The activity needing a destination.
            candidates: Available zones to choose from.
            client: An :class:`~aibm.llm.LLMClient`.

        Returns:
            The same ``activity`` with ``location`` set.

        Raises:
            ValueError: If ``candidates`` is empty.
        """
        if not candidates:
            raise ValueError("candidates must contain at least one Zone")

        if client is None:
            client = create_client(self.model)

        background = self._build_background()
        zones_text = "\n".join(
            f"- {z.id}: {z.name} ({', '.join(k for k, v in z.land_use.items() if v)})"
            for z in candidates
        )
        prompt = (
            f"You are {self.name}, choosing where to do an "
            "activity.\n"
            f"Background:\n{background}\n\n"
            f"Activity type: {activity.type}\n\n"
            f"Candidate zones:\n{zones_text}\n\n"
            "Pick exactly one zone id from the list above "
            "that best fits this activity. Respond with the "
            "zone id and your reasoning."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "zone_id": {"type": "string"},
                    "reasoning": {"type": "string"},
                },
                "required": ["zone_id", "reasoning"],
            },
        )

        data = json.loads(text)
        activity.location = data["zone_id"]
        return activity

    def schedule_activities(
        self,
        activities: list[Activity],
        client: LLMClient | None = None,
    ) -> DayPlan:
        """Ask the LLM to assign start/end times to activities.

        An empty input list returns an empty ``DayPlan`` without
        calling the LLM.

        Args:
            activities: Activities to schedule.
            client: An :class:`~aibm.llm.LLMClient`.

        Returns:
            A ``DayPlan`` sorted by ``start_time``.
        """
        if not activities:
            return DayPlan(activities=[])

        if client is None:
            client = create_client(self.model)

        background = self._build_background()
        activities_text = "\n".join(
            f"- {a.type} "
            f"(flexible: {'yes' if a.is_flexible else 'no'}"
            f", location: {a.location})"
            for a in activities
        )
        prompt = (
            f"You are {self.name}, scheduling your day.\n"
            f"Background:\n{background}\n\n"
            f"Activities to schedule:\n{activities_text}\n\n"
            "Assign a start_time and end_time (in minutes "
            "from midnight, e.g. 480 = 08:00) to each "
            "activity. Fixed activities have realistic fixed "
            "hours; flexible ones fill the remaining time. "
            "Return them in chronological order."
        )

        text = client.generate_json(
            model=self.model,
            prompt=prompt,
            schema={
                "type": "object",
                "properties": {
                    "schedule": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {"type": "string"},
                                "start_time": {"type": "number"},
                                "end_time": {"type": "number"},
                            },
                            "required": [
                                "type",
                                "start_time",
                                "end_time",
                            ],
                        },
                    }
                },
                "required": ["schedule"],
            },
        )

        data = json.loads(text)

        for item in data["schedule"]:
            for activity in activities:
                if activity.type == item["type"]:
                    activity.start_time = item["start_time"]
                    activity.end_time = item["end_time"]
                    break

        sorted_activities = sorted(
            activities,
            key=lambda a: a.start_time if a.start_time is not None else 0,
        )
        return DayPlan(activities=sorted_activities)

    def build_tours(self, day_plan: DayPlan) -> DayPlan:
        """Convert scheduled activities into Trip/Tour objects.

        Builds the sequence home → activity₁ → activity₂ → … → home,
        creating a Trip between each consecutive pair of locations.
        A new Tour starts each time the agent departs from home.

        No LLM call is made — this is pure logic.

        Args:
            day_plan: A DayPlan with scheduled, located activities.

        Returns:
            The same ``day_plan`` with ``tours`` populated.

        Raises:
            ValueError: If ``home_zone`` is not set or any activity
                is missing a location or times.
        """
        if self.home_zone is None:
            raise ValueError("home_zone must be set before building tours")

        for act in day_plan.activities:
            if act.location is None:
                raise ValueError(f"Activity '{act.type}' has no location")
            if act.start_time is None or act.end_time is None:
                raise ValueError(f"Activity '{act.type}' has no scheduled times")

        if not day_plan.activities:
            day_plan.tours = []
            return day_plan

        # Build location sequence: home → activities → home
        locations: list[str] = [self.home_zone]
        for act in day_plan.activities:
            assert act.location is not None
            locations.append(act.location)
        locations.append(self.home_zone)

        # Build departure times: leave home before first activity,
        # leave each activity at its end_time, final arrival home
        times: list[float] = [day_plan.activities[0].start_time or 0]
        for act in day_plan.activities:
            assert act.end_time is not None
            times.append(act.end_time)

        # Create trips between consecutive locations
        all_trips: list[Trip] = []
        for i in range(len(locations) - 1):
            trip = Trip(
                origin=locations[i],
                destination=locations[i + 1],
                departure_time=times[i],
            )
            all_trips.append(trip)

        # Group into tours: new tour each departure from home
        tours: list[Tour] = []
        current_trips: list[Trip] = []
        for trip in all_trips:
            current_trips.append(trip)
            if trip.destination == self.home_zone:
                tours.append(
                    Tour(
                        trips=current_trips,
                        home_zone=self.home_zone,
                    )
                )
                current_trips = []

        # Unclosed tour (shouldn't happen with home appended)
        if current_trips:
            tours.append(Tour(trips=current_trips, home_zone=self.home_zone))

        day_plan.tours = tours
        return day_plan
