"""Zone — a spatial area in the study region."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Zone:
    """A spatial zone (traffic analysis zone) in the study area.

    Zones are external inputs — they are read from OSM or census data, not
    generated by the LLM.

    Attributes:
        id: Unique zone identifier (e.g. a census code or OSM relation id).
        name: Human-readable zone name.
        x: Centroid longitude (or projected x-coordinate).
        y: Centroid latitude (or projected y-coordinate).
        land_use: Dict mapping land-use category names to booleans, e.g.
            ``{"residential": True, "commercial": False, "industrial": False}``.
            Defaults to an empty dict when not provided.
    """

    id: str
    name: str
    x: float
    y: float
    land_use: dict[str, bool] = field(default_factory=dict)
